ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: "style(pre-commit.ci): auto fixes [...]"
  autoupdate_commit_msg: "ci(pre-commit.ci): autoupdate"

repos:
  -   repo: https://github.com/hadialqattan/pycln
      rev: v2.1.3
      hooks:
      - id: pycln

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject

  -   repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.9.9
      hooks:
        - id: ruff
          args: [--fix, --unsafe-fixes]
        - id: ruff-format
